### PR TITLE
Adding HPSynergyGen10 ILO Profile 

### PR DESCRIPTION
**Pull request by viramamur**
Adding HPSynergyGen10 ILO Profile

https://github.com/kentik/snmp-profiles/issues/637

### CODE REVIEW

**Comment by Mesverrum** [comment]
@viramamur I'm not sure I understand this PR, this is a copy of nearly everything in the existing HP ILO profile 
https://github.com/kentik/snmp-profiles/blob/main/profiles/kentik_snmp/hp/hp-ilo.yml

What are you hoping to accomplish or change with this PR?

**Comment by viramamur** [comment]
Actual HP ilo 5 profile is not pulling the details so I have separated it.

**Comment by viramamur** [comment]
We are using ILO5 and with existing profile it was not working, we need a sperate the profile name for our ilo5 Gen10 servers.

**Comment by viramamur** [comment]
@Mesverrum   I reviewed we are using SNMP v1 and we have shared the snmpwalk output seem we need to have new profile hp-ilo5.yml. could you please review the snmpwalk attached on https://github.com/kentik/snmp-profiles/issues/637 and update or create a new profile as hp-ilo5.yml?

**Comment by viramamur** [comment]
@Mesverrum  Could you please review now we able to pull the details after updating the provider and profile on snmp base file. https://github.com/kentik/snmp-profiles/issues/637 ( I have attahced snmpwalk ) is it possible to add the missing oid for hp-ilo.yml. power supply  condition and powersupply status. 

invalid enum
AMP Fault Tolerant Type
invalid enum
AMP State
ok
AMP Condition
other
AMP Hot-Pluggable
other
Power Supply Condition
other
Power Supply Status
ok
ASR Condition
enabled
ASR Status
ok
Thermal Condition
ok
Thermal Status
ok
Fan Status
other
CPU Fan Status
ok
CPU Overall Condition

**Pull request closed without merging**
