### PR TITLE
Update cisco-firepower.yml

### PR DESCRIPTION
**Pull request by al3kh**
added cisco-all-devices.yml & cisco-firepower-asa.yml as extended yml

### CODE REVIEW

**Comment by al3kh** [comment]
@thezackm Hi can you please approve. thanks

**Comment by thezackm** [comment]
@al3kh - thank you for the submission; this PR is going to generate a few conflicts on basic metrics and has a relatively high risk of creating a situation with a large number of failed SNMP polls due to unsupported OIDs in the profiles you're using for `extends`. (_the profile is isolated based on previous SNMP walks received from customers that showed a limited amount of SNMP support compared to a traditional Cisco device_)

Can you identify specifically which OIDs are missing from the existing `cisco-firepower.yml` profile that you are trying to capture with this request?

**Comment by al3kh** [comment]
Hi @thezackm. I am looking for crasNumDeclinedSessions, crasNumSessions, crasMaxSessionsSupportable, crasNumUsers, crasMaxUsersSupportable, crasNumSetupFailInsufResources from cisco-firepower-asa.yml and entPhysicalDescr ,entPhysicalClass, entPhysicalName, entPhysicalSerialNum, entPhysicalModelName from cisco-all-devices.yml

**Comment by al3kh** [comment]
Hi @thezackm. The sysoid for the device is ".1.3.6.1.4.1.9.1.2404". Also PFA the snmpwalk output on the sample device.
[snmpwalkfpr.txt](https://github.com/kentik/snmp-profiles/files/13292570/snmpwalkfpr.txt)

**Comment by thezackm** [comment]
@al3kh - take a look at PR #719 and see if it meets your needs.

**Comment by al3kh** [comment]
@thezackm LGTM

**Comment by thezackm** [comment]
closing this one, addressing the need in #719

**Pull request closed without merging**
