### PR TITLE
Create fortinet-fortiap.yml

### PR DESCRIPTION
**Pull request by al3kh**
Created new profile for fortinet access points

### CODE REVIEW

**Comment by al3kh** [comment]
@Mesverrum can you please approve this

**Comment by thezackm** [comment]
@al3kh - thank you for the submission; can you please provide a copy of the `FORTINET-FORTIAP-MIB`? I'm not seeing any references available on the public internet unfortunately.

Additionally; please share a sanitized output from a SNMP walk on a test AP in your environment so we can evaluate the results against this profile and make sure it's going to work for your needs.

[download instructions are here if you need them](https://docs.fortinet.com/document/fortiap/7.4.1/fortiwifi-and-fortiap-configuration-guide/930384/monitoring-fortiap-with-snmp)

**Comment by al3kh** [comment]
Hi @thezackm ,
Please find the requested files below.

[snmpwalkAP.txt](https://github.com/kentik/snmp-profiles/files/12752893/snmpwalkAP.txt)
[FORTINET-FORTIAP-MIB-build0178.zip](https://github.com/kentik/snmp-profiles/files/12752896/FORTINET-FORTIAP-MIB-build0178.zip)

**Comment by thezackm** [comment]
@al3kh - looks like there was a timeout on that walk maybe; try this one to target the MIB directly:

```
snmpwalk -v 2c -On -c $COMMUNITY $IP_ADDRESS .1.3.6.1.4.1.12356.120.2
```

**Comment by al3kh** [comment]
@thezackm Hi, let me know if you can see the output.
[snmpwalk.txt](https://github.com/kentik/snmp-profiles/files/12753036/snmpwalk.txt)

**Review by thezackm — APPROVED** [review]

**Comment by thezackm** [comment]
@al3kh - thanks again for the submission; this will be live in ~30 minutes on the latest image of the ktranslate agent. 

you can find the results using a NRQL query like this:

```sql
FROM Metric SELECT
  latest(fapWtpWanMode),
  latest(fapWtpApAddrMode)
FACET
  fapHostName,
  fapVersion,
  fapSerialNum,
  fapRegionCode,
  fapBaseMacAddr,
  fapBiosVer,
  fapBiosDataVer,
  fapSysPartNum,
  fapWtpApIpAddr,
  fapWtpApIpNetmask,
  fapWtpApDnsAddr,
  fapWtpApAcAddr1,
  fapWtpApAcAddr2,
  fapWtpApAcAddr3,
  fapWtpApAcHostname1,
  fapWtpApAcHostname2,
  fapWtpApAcHostname3,
  fapWtpLocation
WHERE provider = 'kentik-fortinet-ap'
```

**Comment by al3kh** [comment]
Hi @thezackm As we created a new docker for the access points, its not pulling the latest image of the fortinet-fortiap profile and they are still showing under kentik-default. FYI we have added FORINET-FORTIAP-MIB under mibs_enabled in the snmp config file. Can you please help us out on this. Thankyou

**Comment by thezackm** [comment]
They will remain under the `KENTIK_DEFAULT` entity type unless there is an update to the [entity definition](https://github.com/newrelic/entity-definitions). You'll need to open a support case with New Relic to have that change made.

**Pull request merged**
